version: '3.8'

services:
  web:
    build: deploy
    ports:
    - 8090:5000
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: password
    ports:
    - 5432:5432
    restart: on-failure
    volumes:
    - ./devdata/postgres/:/var/lib/postgresql/data
    depends_on:
    - pgadmin
  pgadmin:
    image: dpage/pgadmin4
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@databasefiller.ru
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
    - 8080:80
    volumes:
    - ./devdata/pgadmin/:/var/lib/pgadmin