// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Web.Data;

namespace Web.Migrations
{
    [DbContext(typeof(SpeedrunDbContext))]
    partial class SpeedrunDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Models.GameCategoryModerator", b =>
                {
                    b.Property<string>("GameId")
                        .HasColumnType("text");

                    b.Property<string>("CategoryId")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("GameId", "CategoryId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("GameCategoryModerators");
                });

            modelBuilder.Entity("Models.PulseMessage", b =>
                {
                    b.Property<string>("GameId")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("SendTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.HasKey("GameId", "UserId", "SendTime");

                    b.HasIndex("UserId");

                    b.ToTable("PulseMessages");
                });

            modelBuilder.Entity("SpeedrunAppBack.Models.UserModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("IsRunner")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SpeedrunAppBack.Models.UserSubscription", b =>
                {
                    b.Property<string>("User1Id")
                        .HasColumnType("text");

                    b.Property<string>("User2Id")
                        .HasColumnType("text");

                    b.HasKey("User1Id", "User2Id");

                    b.HasIndex("User2Id");

                    b.ToTable("UserSubscriptions");
                });

            modelBuilder.Entity("Models.GameCategoryModerator", b =>
                {
                    b.HasOne("SpeedrunAppBack.Models.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Models.PulseMessage", b =>
                {
                    b.HasOne("SpeedrunAppBack.Models.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SpeedrunAppBack.Models.UserSubscription", b =>
                {
                    b.HasOne("SpeedrunAppBack.Models.UserModel", "User1")
                        .WithMany("SubscribtionsTo")
                        .HasForeignKey("User1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpeedrunAppBack.Models.UserModel", "User2")
                        .WithMany("SubscribtionsFrom")
                        .HasForeignKey("User2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User1");

                    b.Navigation("User2");
                });

            modelBuilder.Entity("SpeedrunAppBack.Models.UserModel", b =>
                {
                    b.Navigation("SubscribtionsFrom");

                    b.Navigation("SubscribtionsTo");
                });
#pragma warning restore 612, 618
        }
    }
}
